# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chapter 7 Challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chapter 7 Challenge
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
end
