#pp Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift Example Chapter 3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift Example Chapter 3
  pod 'RxSwift', '~> 5.1'
  pod 'RxCocoa', '~> 5.1'
end
