# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FilteringOperations' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# Pods for FilteringOperations
 pod 'RxSwift', '5.1.1'
 pod 'RxCocoa', '5.1.1'
end
